---
- hosts: all
  roles:
    - kde-common
    - qt-dev
  vars:
    user: "vagrant"
    homedir: "/home/vagrant/"
    toolsdir: "{{homedir}}/tools/"
    desktop_environment: "KDE"
    git_install_gui: true
    git_install_git_cola: true
    username: "iatanasov77"
    usermail: "i.atanasov77@gmail.com"
    use_android: false
    use_raspi: false
    
    # Original QT Version was: 5.14.1
    ###################################
    qt_version_major: 5.15
    qt_version_minor: 2
    qt_version_full: "5.14.1"
