---
- hosts: all
  pre_tasks:
    - name: Install Python PIP
      become: true
      apt:
        name:
          #  Package 'python-pip' has no installation candidate
          # in Ubuntu 21.04
          #######################################################
          #- 'python-pip'
          - 'python3-pip'
        state: present

    - name: Use Python3 as Default Interpreter
      become: true
      file:
        src: "/usr/bin/python3"
        path: "/usr/bin/python"
        state: link
        force: yes
    
    # pymysql require Python3
    # ------------------------
    # Into inventory file add: ansible_python_interpreter	= /usr/bin/python3
    # Or: ln -sf /usr/bin/python3 /usr/bin/python
    ###############################################################################
    - name: Make sure pymysql is present
      become: true
      pip:
        name: pymysql
        state: present

  vars:
    keyboard_layout: "us,bg"
    keyboard_variant: ",phonetic"
    installbuilder_version: 21.6.0
    # This made kde to crash
    # ----------------------
    # with: virtualbox does not support mouse pointer integration in the current video mode
    # on syslog writes: sddm.service: Failed with result 'core-dump'
    ##########################################################################################
    #install_wine: true
    #
    vs_qt_version_major: 5.15
    vs_qt_version_minor: 2
    vs_qt_download: true

  roles:
    - keyboard-layout
    - vs-qt-dev

  tasks:
    - name: Set Timezone to Europe/Sofia
      shell: timedatectl set-timezone Europe/Sofia
      become: true

    - name: Install Usefull Packages
      apt:
        # PHP is needed for bumpversion script, the others you kknow what its are
        name: ['php', 'git-flow', 'mc', 'dos2unix', 'vim', 'zstd', 'gdb', 'gdbserver']
        state: present
      become: true

    - name: Install BumpVersion Script
      get_url:
        url: https://github.com/iatanasov77/bumpversion/raw/v0.4.1/bumpversion.php
        dest: /usr/local/bin/bumpversion
        mode: '0777'
      become: true

    - name: Terminate KDE Session
      shell: loginctl terminate-user "vagrant"

# Build Qt with 'sudo vs-compile-qt.sh' and add qmake to path 'sudo ln -sf /home/vagrant/tools/qt-5.14.1/x86_64/bin/qmake /usr/bin/qmake'
# Create Project with 'qmake -project' and add line 'QT += widgets' to the project_name.pro files
# Run 'qmake'
